
communicateNeighbourMAC: communicateNeighbourMAC.o
	$(CC) $(LDFLAGS) communicateNeighbourMAC.o -o communicateNeighbourMAC

communicateNeighbourMAC.o: communicateNeighbourMAC.c
	$(CC) $(CFLAGS) -c communicateNeighbourMAC.c

clean:
	rm *.o communicateNeighbourMAC
